// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kol2.Context;

#nullable disable

namespace kol2.Migrations
{
    [DbContext(typeof(myContext))]
    [Migration("20240624105509_Init6")]
    partial class Init6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kol2.Models.Backpack", b =>
                {
                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("Ammount")
                        .HasColumnType("int");

                    b.HasKey("IdCharacter", "IdItem");

                    b.HasIndex("IdItem");

                    b.ToTable("Backpacks");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            IdItem = 2,
                            Ammount = 1
                        },
                        new
                        {
                            IdCharacter = 2,
                            IdItem = 1,
                            Ammount = 2
                        });
                });

            modelBuilder.Entity("kol2.Models.Character", b =>
                {
                    b.Property<int>("IdCharacter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCharacter"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("IdCharacter");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            CurrentWeight = 10,
                            FirstName = "roman",
                            LastName = "fuskii",
                            MaxWeight = 40
                        },
                        new
                        {
                            IdCharacter = 2,
                            CurrentWeight = 12,
                            FirstName = "dd",
                            LastName = "vcvc",
                            MaxWeight = 50
                        });
                });

            modelBuilder.Entity("kol2.Models.Character_title", b =>
                {
                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdTitle")
                        .HasColumnType("int");

                    b.Property<DateTime>("AquiredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCharacter", "IdTitle");

                    b.HasIndex("IdTitle");

                    b.ToTable("CharacterTitles");

                    b.HasData(
                        new
                        {
                            IdCharacter = 1,
                            IdTitle = 1,
                            AquiredAt = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdCharacter = 2,
                            IdTitle = 2,
                            AquiredAt = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("kol2.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Name = "oksy",
                            Weight = 20
                        },
                        new
                        {
                            IdItem = 2,
                            Name = "Anna",
                            Weight = 15
                        });
                });

            modelBuilder.Entity("kol2.Models.Title", b =>
                {
                    b.Property<int>("IdTitle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTitle"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTitle");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            IdTitle = 1,
                            Name = "zzz"
                        },
                        new
                        {
                            IdTitle = 2,
                            Name = "ccc"
                        });
                });

            modelBuilder.Entity("kol2.Models.Backpack", b =>
                {
                    b.HasOne("kol2.Models.Character", "Character")
                        .WithMany("Backpacks")
                        .HasForeignKey("IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kol2.Models.Item", "Item")
                        .WithMany("Backpacks")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("kol2.Models.Character_title", b =>
                {
                    b.HasOne("kol2.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kol2.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("IdTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("kol2.Models.Character", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("kol2.Models.Item", b =>
                {
                    b.Navigation("Backpacks");
                });

            modelBuilder.Entity("kol2.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
